# Generated by Django 3.2.8 on 2022-01-05 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_email_varifird',
            field=models.BooleanField(default=False),
        ),
    ]
